# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Krone.dev
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krone.dev" # the base hostname & protocol for your site, e.g. http://example.com

twitter: 
  name: kronetwit
  icon: assets/img/twitterLg.png
  link: https://twitter.com
github: 
  name: kronephon
  icon: assets/img/githubLg.png
  link: https://github.com/kronephon
linkedin: 
  name: pedropim
  icon: assets/img/linkedinLg.png
  link: https://www.linkedin.com/in/pedropim
instagram: 
  name: krone.ig
  icon: assets/img/instagramLg.png
  link: https://www.instagram.com/krone.ig/
email: 
  name: pedro.f.pim@gmail.com
  icon: assets/img/emailLg.png
  link: mailto:pedro.f.pim@gmail.com
bitcoin: 
  name: bitcoinaddress
  icon: assets/img/bitcoinLg.png
  link: bitcoinurlsomething

searchIndex: /pages/searchIndex.csv

# Build settings
plugins:
  - jekyll-feed